config/routes.rb
Rails.application.routes.draw do

	root 	 'static_pages#home'
	get  	 '/about',   to: 'static_pages#about'
	get  	 '/login',   to: 'sessions#new'
	post 	 '/login',   to: 'sessions#create'
	delete '/logout',  to: 'sessions#destroy'

	resources :users do
		member do
			get 	:messages
			patch :unassign_cohort
			patch :soft_delete
			patch :reactivate
		end
		delete  :destroy_soft_deleted, on: :collection
	end

	resources :cohorts do
		member do
			get 	:select_users
			patch :add_users
		end
	end

	resources :messages, only: :create do
		patch 	:open, on: :member
	end

	resources :outside_messages, only: [:new, :create] do
		patch		:open, on: :member
	end

	resources :account_activations, only: 	[:edit]
	resources :password_resets,		  only: 	[:new, :create, :edit, :update]
	resources :posts,								except: [:index, :show, :new]
	resources :comments,						only: 	[:create, :destroy]
	resources :user_goals, 					only: 	[:create, :destroy]
end

app/models/message.rb
class Message < ApplicationRecord

	belongs_to :from_user, class_name: "User"
	belongs_to :to_user, 	 class_name: "User"

	default_scope -> { order(created_at: :desc) }

	validates :to_user_id, presence: true
	validates :body, 			 presence: true, length: { within: 1..3000 }

	def open_message
		toggle!(:opened)
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	before_action :require_login

	def create
		@message = current_user.sent_messages.build(message_params)
		@user = User.find(params[:message][:to_user_id])
		if @message.save
			flash[:success] = "Message was sent"
			redirect_to @user
		else
			render "users/show"
		end
	end

	def open
		@message = Message.find(params[:id])
		@message.open_message if !@message.opened?
		@unopened_count = Message.where(to_user_id: @message.to_user_id).where(opened: false).count
		respond_to do |format|
			format.html { redirect_to current_user }
			format.js
		end
	end

	private

	def message_params
		params.require(:message).permit(:body, :to_user_id)
	end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_message.html.erb
<li class="list-group-item list-group-item-dark">

	<!-- New Message Badge -->
	<% if (box == "inbox") && !message.opened? %>
		<div id="<%= box %>-badge-<%= message.id %>">
			<span class="badge badge-primary">New Message</span>
		</div>
	<% end %>

	<!-- Message Data -->
	<% if box == "inbox" %>
		From <%= link_to message.from_user.name, message.from_user %> 
	<% else %>
		To <%= link_to message.to_user.name, message.to_user %> 
	<% end %>
	on <%= format_time(message.created_at) %>

	<!-- Message Body -->
	<div>
		<%= "#{message.body[0..20]}" %>
		<%= content_tag :span, message.body[21..-1],
										class: "collapse", id: "#{box}-#{message.id}" %>
		<% if box == "inbox" %>
			<%= button_to "Open/Close", open_message_path(message),
										method: :patch, remote: true, class: "btn-sm",
										data: { toggle: "collapse",
														target: "#inbox-#{message.id}" } %>
		<% else %>
			<br><%= content_tag :button, "Open/Close", 
													class: "btn btn-sm",
													data: { toggle: "collapse",
																	target: "#sent-#{message.id}" } %> 
		<% end %>
	</div>
</li>

app/views/messages/open.js.erb
<% if @unopened_count > 0 %>
	$("#inbox-badge").html("<%= @unopened_count %> New");
<% else %>
	$("#inbox-badge").hide();
<% end %>

$("#inbox-badge-<%= @message.id %>").hide();