config/routes.rb
Rails.application.routes.draw do

	root 	 'static_pages#home'
	get  	 '/about',   to: 'static_pages#about'
	get  	 '/login',   to: 'sessions#new'
	post 	 '/login',   to: 'sessions#create'
	delete '/logout',  to: 'sessions#destroy'

	resources :users do
		member do
			get 	:messages
			patch :unassign_cohort
			patch :soft_delete
			patch :reactivate
		end
		delete  :destroy_soft_deleted, on: :collection
	end

	resources :cohorts do
		member do
			get 	:select_users
			patch :add_users
		end
	end

	resources :messages, only: :create do
		patch 	:open, on: :member
	end

	resources :outside_messages, only: [:new, :create] do
		patch		:open, on: :member
	end

	resources :account_activations, only: 	[:edit]
	resources :password_resets,		  only: 	[:new, :create, :edit, :update]
	resources :posts,								except: [:index, :show, :new]
	resources :comments,						only: 	[:create, :destroy]
	resources :user_goals, 					only: 	[:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token, :activation_token, :pass_reset_token

  belongs_to :cohort,            optional: true
  has_many   :sent_messages,     foreign_key: :from_user_id, class_name: "Message", dependent: :destroy
  has_many   :received_messages, foreign_key: :to_user_id,   class_name: "Message", dependent: :destroy
  has_many   :posts,             foreign_key: :author_id
  has_many   :comments,          foreign_key: :author_id, dependent: :destroy
  has_many   :goals,             class_name: "UserGoal",  dependent: :destroy

  default_scope           -> { order(:name) }
  scope :only_deleted,    -> { where.not(deleted_at: nil) }
  scope :without_deleted, -> { where(deleted_at: nil) }

	before_save       :downcase_email
  before_create     :create_activation_digest
  before_validation :create_temp_password, on: :create
  after_create      :delete_temp_password_digest

	validates :name,  presence: true, length: { within: 3..25 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { within: 5..254 },
										format: { with: VALID_EMAIL_REGEX },
										uniqueness: { case_sensitive: false}

	has_secure_password
  # Password must have at least one lower alpha, one upper alpha, and one number
  VALID_PASSWORD_REGEX = /(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])./
	validates :password, presence: true, length: { within: 6..40 },
                       format: { with: VALID_PASSWORD_REGEX,
                                 message: "must have at least one lowercase letter,
                                           one uppercase letter, and one number" },
                       allow_nil: true

	# Returns the hash digest of the given string.
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a new random token
  def self.new_token
  	SecureRandom.urlsafe_base64
  end

  # Remembers user in the database for use in persistent cookies
  def remember
  	self.remember_token = User.new_token
  	update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
  	update_attribute(:remember_digest, nil)
  end

  # Returns true if given token matches digest
  def authenticated?(attribute, token)
  	digest = send("#{attribute}_digest")
  	return false if digest.nil?
  	BCrypt::Password.new(digest).is_password?(token)
  end

  # Activates a user
  def activate
    update_columns(activated:    true,
                   activated_at: Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def create_reset_digest
    self.pass_reset_token = User.new_token
    update_columns(reset_digest:  User.digest(pass_reset_token),
                   reset_sent_at: Time.zone.now)
  end

  # Returns true if reset has expired
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # Removes user from cohort
  def unassign_cohort
    update_attribute(:cohort_id, nil)
  end

  # Marks a user as deleted without deleting the record
  def soft_delete
    update_columns(deleted_at:      Time.zone.now,
                   cohort_id:       nil,
                   password_digest: nil,
                   remember_digest: nil,
                   activated:       false)
  end

  # Unmarks user as soft deleted and restarts activation process
  def reactivate
    self.activation_token = User.new_token
    update_columns(deleted_at: nil,
                   activation_digest: User.digest(activation_token))
    send_activation_email
  end

  # Returns a count of unopened messages
  def new_message_count
    count  = Message.where(to_user_id: self.id).where(opened: false).count
    count += OutsideMessage.where(opened: false).count if self.admin?
    count
  end

	private

	def downcase_email
		self.email.downcase!
	end

  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

  def create_temp_password
    self.password = self.password_confirmation = User.new_token
  end

  # Nullifies (temporary) password_digest for security
  def delete_temp_password_digest
    update_attribute(:password_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :require_login
	before_action :require_admin, 			 		 except: [:show, :edit, :update, :messages]
	before_action :require_current_user, 		 only: 	 [:edit, :update, :messages]
	before_action :require_deactivated_user, only: 	 :reactivate

	def index
		@active 		  = User.includes(:cohort).where(activated: true)
		@unactivated  = User.without_deleted.where(activated: false)
		@soft_deleted = User.only_deleted
	end

	def show
		@user = User.find(params[:id])
		if current_user?(@user)
			@user_goal 		 			= UserGoal.new
			@new_message_count  = @user.new_message_count
		else
			@message = Message.new
		end
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params_create)
		if @user.save
			@user.send_activation_email
			flash[:success] = "Account activation email sent to client"
			redirect_to current_user
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @user.update_attributes(user_params_update)
			flash[:success] = "Information updated"
			redirect_to @user
		else
			render :edit
		end
	end

	def unassign_cohort
		@user = User.find(params[:id])
		@user.unassign_cohort
		flash[:success] = "User removed from cohort"
		redirect_back fallback_location: @user
	end

	def soft_delete
		User.find(params[:id]).soft_delete
		flash[:success] = "User archived and marked for deletion"
		redirect_to users_path
	end

	def reactivate
		@user.reactivate
		flash[:success] = "Reactivation email sent to client"
		redirect_to users_path
	end

	def destroy
		User.find(params[:id]).destroy
		flash[:success] = "User permanently deleted"
		redirect_to users_path
	end

	def destroy_soft_deleted
		User.only_deleted.destroy_all
		flash[:success] = "All archived users permanently deleted"
		redirect_to users_path
	end

	def messages
		@sent 							= Message.includes(:to_user).where(from_user_id: @user.id)
		@received 					= Message.includes(:from_user).where(to_user_id: @user.id)
		@received_unopened  = @received.where(opened: false).count
		if @user.admin?
			@outside 					= OutsideMessage.where(to_admin_id: @user.id)
			@outside_unopened = @outside.where(opened: false).count
		end
	end

	private

	# User creates password after activation
	def user_params_create
		params.require(:user).permit(:name, :email)
	end

	def user_params_update
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

	# Before Filters

	def require_current_user
		@user = User.find(params[:id])
		redirect_to root_path unless current_user?(@user)
	end

	def require_deactivated_user
		@user = User.find(params[:id])
		redirect_to root_path if @user.activated?
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <% if local_assigns[:edit] %>
	  <%= f.label :password %>
	  <%= f.password_field :password, class: 'form-control' %>

	  <%= f.label :password_confirmation, "Confirm Password" %>
	  <%= f.password_field :password_confirmation, class: 'form-control' %>
  <% end %>

  <%= f.submit yield(:button_text), class: "btn btn-sm" %>
<% end %>

app/views/users/_message_box.html.erb
<div class="card">
  <div class="card-header">
    <a class="<%= a_class %>" data-toggle="collapse" href="#<%= collapse_num %>">
      <%= box.capitalize %> 
    </a>
    
    <% if (box != "sent") && (unopened_count > 0) %>
	    <span id="<%= box %>-badge" class="badge badge-primary"><%= unopened_count %> New</span>
    <% end %>
  
  </div>
  <div id="<%= collapse_num %>" class="collapse" data-parent="#accordion">
    <div class="card-body">
      <% if messages.any? %>
				<ol class="list-group">
					<%= render messages, box: box %>
				</ol>
			<% else %>
				No messages
			<% end %>
    </div>
  </div>
</div>

app/views/users/_show_mine.html.erb
<div class="container">
	<div class="row">
		<div class="col">
				My Cohort: <%= @user.cohort ? (link_to @user.cohort.name, @user.cohort) :
																			"currently unassigned" %><br>
				<%= link_to "My Messages", messages_user_path(@user) %> 
				<% if @new_message_count > 0 %>
      		<span class="badge badge-primary"><%= @new_message_count %> New</span>
      	<% end %>
		</div>
		<div class="col-1"></div>
		<div class="col border border-secondary rounded">
			<% if @user.cohort %>
				Cohort Goals:<br>
				<ol class="list-group">
					<%= render @user.cohort.goals %>
				</ol><br>
			<% end %>
			Personal Goals:
			<ol id="user-goals-list" class="list-group">
				<% if @user.goals.any? %>
					<%= render @user.goals %>
				<% end %>
			</ol>
			<%= form_for @user_goal, remote: true do |f| %>

				<%= hidden_field_tag :user_id, @user.id %>
				<%= f.text_area :body, class: "form-control", id: "goal-box",
															 placeholder: "Add a personal goal" %>
				<%= f.submit "Add", class: "btn btn-sm" %>
			<% end %>
		</div>
	</div>
</div>

app/views/users/_show_other.html.erb
<div class="container">
	<div class="row">
		<div class="col">
			<%= form_for @message do |f| %>

				<%= render "shared/error_messages", object: f.object %>

				<%= f.hidden_field :to_user_id, value: @user.id %>
				<%= f.text_area :body, class: "form-control",
															 placeholder: "Send a message to #{@user.name}" %><br>
				<%= f.submit "Send", class: "btn btn-sm" %>
			<% end %>
		</div>
		<div class="col"></div>
	</div>
</div>

app/views/users/_user.html.erb
<li class="list-group-item list-group-item-dark">

	<!-- Cohorts#show -->
	<% if local_assigns[:participant] %>
		<%= link_to user.name, user %>
		<% if current_user.admin? %>
			<%= button_to "remove from cohort", unassign_cohort_user_path(user),
										method: :patch, class: "btn-secondary btn-sm" %>
		<% end %>

	<!-- Users#Index Active -->
	<% elsif local_assigns[:active] %>
		<%= link_to user.name, user %>
		<br>Cohort: <%= user.cohort ? (link_to user.cohort.name, user.cohort) :
																	"unassigned" %><br>
		Active since <%= format_time(user.activated_at) %><br>
		<% if !user.admin? %> 
			<%=button_to "delete client", soft_delete_user_path(user),
										method: :patch, class: "btn-secondary btn-sm",
										data: { confirm: "Mark user for deletion?" } %>
		<% end %>

	<!-- Users#Index Deleted -->
	<% elsif local_assigns[:deleted] %>
		<%= user.name %> was deleted <%= format_time(user.deleted_at) %>
		<%= button_to "reactivate", reactivate_user_path(user),
									method: :patch, class: "btn-secondary btn-sm",
									data: { confirm: "Send client a reactivation email?" } %>
		<%= button_to "permanently delete", user,
									method: :delete, class: "btn-dark btn-sm",
									data: { confirm: "Permanently erase all information for this client?" } %>

	<!-- Users#Index Inactive -->
	<% elsif local_assigns[:inactive] %>
		<%= user.name %> was invited <%= format_time(user.created_at) %>
		<% if !user.admin? %> 
			<%=button_to "delete client", user,
										method: :delete, class: "btn-dark btn-sm",
										data: { confirm: "Are you sure?" } %>
		<% end %>
	<% end %>
</li>

app/views/users/edit.html.erb
<% provide :title,       "Edit" %>
<% provide :button_text, "Update" %>

<h1>Edit My Information</h1>

<%= render "form", edit: true %>

app/views/users/index.html.erb
<% provide :title, "Clients" %>

<h1>All Users</h1>

<h2>Active Clients</h2>
<% if @active.any? %>
	<ol class="list-group">
		<%= render @active, active: true %>
	</ol>
<% else %>
	<p>
		No active clients at this time.
		<%= link_to "Invite New Client", new_user_path %>
	</p>
<% end %>

<h2>Deleted Clients</h2>
<% if @soft_deleted.any? %>
	<%= button_to "Permanently Delete All", destroy_soft_deleted_users_path,
								method: :delete, class: "btn-dark btn-sm",
								data: { confirm: "Permanently erase all information for deleted clients?" } %>
	<ol class="list-group">
		<%= render @soft_deleted, deleted: true %>
	</ol>
<% else %>
	<p>No deleted clients at this time.</p>
<% end %>

<h2>Inactive Clients</h2>
<% if @unactivated.any? %>
	<ol class="list-group">
		<%= render @unactivated, inactive: true %>
	</ol>
<% else %>
	<p>
		No inactive clients at this time.
		<%= link_to "Invite New Client", new_user_path %>
	</p>
<% end %>

app/views/users/messages.html.erb
<% provide :title, "Messages" %>

<h1>My Messages</h1>

<div id="accordion">

	<!-- Inbox -->
  <%= render partial: 	"message_box",
  											locals: { messages: @received, unopened_count: @received_unopened,
  											box: "inbox", a_class: "card-link", collapse_num: "collapseOne" } %>

	<!-- Sent -->
  <%= render partial: 	"message_box",
  											locals: { messages: @sent,
  											box: "sent", a_class: "card-link collapsed", collapse_num: "collapseTwo" } %>

	<!-- Contact -->
  <% if @user.admin? %>
  	<%= render partial: "message_box",
  											locals: { messages: @outside,  unopened_count: @outside_unopened,
  											box: "contact", a_class: "card-link collapsed", collapse_num: "collapseThree" } %>
	<% end %>
</div>

app/views/users/new.html.erb
<% provide :title, 			 "New User" %>
<% provide :button_text, "Invite Client" %>

<h1>Invite New Client</h1>

<%= render "form" %>

app/views/users/show.html.erb
<% provide :title, "#{@user.name}" %>

<h1><%= @user.name %></h1>

<% if current_user?(@user) %>
	<%= render "users/show_mine" %>
<% else %>
	<%= render "users/show_other" %>
<% end %>