config/routes.rb
Rails.application.routes.draw do

	root 	 'static_pages#home'
	get  	 '/about',   to: 'static_pages#about'
	get  	 '/login',   to: 'sessions#new'
	post 	 '/login',   to: 'sessions#create'
	delete '/logout',  to: 'sessions#destroy'

	resources :users do
		member do
			get 	:messages
			patch :unassign_cohort
			patch :soft_delete
			patch :reactivate
		end
		delete  :destroy_soft_deleted, on: :collection
	end

	resources :cohorts do
		member do
			get 	:select_users
			patch :add_users
		end
	end

	resources :messages, only: :create do
		patch 	:open, on: :member
	end

	resources :outside_messages, only: [:new, :create] do
		patch		:open, on: :member
	end

	resources :account_activations, only: 	[:edit]
	resources :password_resets,		  only: 	[:new, :create, :edit, :update]
	resources :posts,								except: [:index, :show, :new]
	resources :comments,						only: 	[:create, :destroy]
	resources :user_goals, 					only: 	[:create, :destroy]
end

app/models/user_goal.rb
class UserGoal < ApplicationRecord

	belongs_to :user

	validates :body, 		presence: true, length: { maximum: 250 }
	validates :user_id, presence: true
end

app/controllers/user_goals_controller.rb
class UserGoalsController < ApplicationController

	before_action :require_login
	before_action :require_current_user

	def create
		@user_goal = @user.goals.build(goal_params)
		respond_to do |format|
			if @user_goal.save
				format.html { redirect_to @user }
				format.js
			else
				@user.goals.delete(@user_goal)
				@new_message_count = @user.new_message_count
				format.html { render 'users/show' }
			end
		end
	end

	def destroy
		@user_goal = UserGoal.find(params[:id])
		@user_goal.destroy
		respond_to do |format|
			format.html { redirect_to @user }
			format.js
		end
	end

	private

	def goal_params
		params.require(:user_goal).permit(:body)
	end

	# Before Filter

	def require_current_user
		@user = User.find(params[:user_id])
		redirect_to root_path unless current_user?(@user)
	end
end

app/helpers/user_goals_helper.rb
module UserGoalsHelper
end

app/views/user_goals/_user_goal.html.erb
<li class="list-group-item list-group-item-dark" id="user-goal-<%= user_goal.id %>">
	<%= user_goal.body %><br>
	<%= button_to "delete", user_goal_path(user_goal),
													method: :delete, remote: true,
													class: "btn-sm",
													params: { user_id: user_goal.user_id } %>
</li>

app/views/user_goals/create.js.erb
$("<%= escape_javascript(render @user_goal) %>").appendTo("#user-goals-list");

$("#goal-box").val("");

app/views/user_goals/destroy.js.erb
$("#user-goal-<%= @user_goal.id %>").hide();