config/routes.rb
Rails.application.routes.draw do

	root 	 'static_pages#home'
	get  	 '/about',   to: 'static_pages#about'
	get  	 '/login',   to: 'sessions#new'
	post 	 '/login',   to: 'sessions#create'
	delete '/logout',  to: 'sessions#destroy'

	resources :users do
		member do
			get 	:messages
			patch :unassign_cohort
			patch :soft_delete
			patch :reactivate
		end
		delete  :destroy_soft_deleted, on: :collection
	end

	resources :cohorts do
		member do
			get 	:select_users
			patch :add_users
		end
	end

	resources :messages, only: :create do
		patch 	:open, on: :member
	end

	resources :outside_messages, only: [:new, :create] do
		patch		:open, on: :member
	end

	resources :account_activations, only: 	[:edit]
	resources :password_resets,		  only: 	[:new, :create, :edit, :update]
	resources :posts,								except: [:index, :show, :new]
	resources :comments,						only: 	[:create, :destroy]
	resources :user_goals, 					only: 	[:create, :destroy]
end

app/views/layouts/_IE_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_admin_links.html.erb
<li class="nav-item dropdown">
	<a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">Administration</a>
	<div class="dropdown-menu">
			<%= link_to "See Client List", 	 users_path, class: "dropdown-item" %>
			<%= link_to "Invite New Client", new_user_path, class: "dropdown-item" %>
			<div class="dropdown-divider"></div>
			<%= link_to "See Cohort List", 	 cohorts_path, class: "dropdown-item" %>
			<%= link_to "Create New Cohort", new_cohort_path, class: "dropdown-item" %>
	</div>
</li>

app/views/layouts/_footer.html.erb
<footer class="fixed-bottom bg-dark">
	<div class="container">
		<div class="row">
			<div class="col">
				<small class="text-white">[footer items here]</small>
			</div>
			<div class="col">
				<nav class="navbar navbar-dark justify-content-end">
					<ul class="navbar-nav">
						<li class="nav-item"><%= link_to 'Home', root_path, class: "nav-link" %></li>
					</ul>
				</nav>
			</div>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header>
	<nav class="navbar bg-dark navbar-dark navbar-expand-sm">
		<div class="container">
			<div class="col">
				<%= link_to 'HealthUp', root_path, class: "navbar-brand" %>
			</div>
			<div class="col">
				<ul class="navbar-nav justify-content-end">
					<li class="nav-item"><%= link_to 'Home', 		root_path, 								class: "nav-link" %></li>
					<li class="nav-item"><%= link_to 'About', 	about_path, 							class: "nav-link" %></li>
					<li class="nav-item"><%= link_to 'Contact', new_outside_message_path, class: "nav-link" %></li>
					<% if logged_in? %>
						<li class="nav-item dropdown">
							<a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">My Account</a>
							<div class="dropdown-menu">
									<%= link_to "Profile", current_user, class: "dropdown-item" %>
									<%= link_to "Cohort", current_user.cohort, class: "dropdown-item" if current_user.cohort %> 
									<%= link_to "Messages", messages_user_path(current_user), class: "dropdown-item" %>
									<%= link_to "Edit Information", edit_user_path(current_user), class: "dropdown-item" %>
							</div>
						</li>
						<% if current_user.admin? %>
							<%= render 'layouts/admin_links' %>
						<% end %>
						<li class="nav-item"><%= link_to 'Log Out', logout_path,
																		 method: :delete, class: "nav-link" %></li>
					<% else %>
						<li class="nav-item"><%= link_to 'Log In', login_path, class: "nav-link" %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/IE_shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <div class="container">
      <div class="jumbotron">
        <%= yield %>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>